MyCompany/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyCompany.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Enter UserName")]
        [Display(Name = "Login")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Enter Password")]
        [UIHint("password")]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

MyCompany/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MyCompany/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

MyCompany/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

MyCompany/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Models;

namespace MyCompany.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }   
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyCompany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

MyCompany/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

MyCompany/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>

@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

MyCompany/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

MyCompany/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

MyCompany/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

MyCompany/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />

MyCompany/Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    &copy; @Config.CompanyName. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
                </div>

            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наши услуги</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/MetatagsPartial.cshtml
@using MyCompany.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if(ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if(ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description"/>
}
@if(ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords"/>
}

MyCompany/Views/Shared/ScriptsPartial.cshtml
@*<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/browser.min.js"></script>
<script src="assets/js/breakpoints.min.js"></script>
<script src="assets/js/util.js"></script>
<script src="assets/js/main.js"></script>*@

<scrpit src="~/js/scripts.min.js" asp-append-version="true"></scrpit>

MyCompany/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">

	<section>
		<h2>Who are you guys?</h2>
		<ul class="small-image-list">
			<li>
				<a href="#"><img src="images/pic2.jpg" alt="" class="left" /></a>
				<h4>Jane Anderson</h4>
				<p>Varius nibh. Suspendisse vitae magna eget et amet mollis justo facilisis amet quis.</p>
			</li>
			<li>
				<a href="#"><img src="images/pic1.jpg" alt="" class="left" /></a>
				<h4>James Doe</h4>
				<p>Vitae magna eget odio amet mollis justo facilisis amet quis. Sed sagittis consequat.</p>
			</li>
		</ul>
	</section>

	<section>
		<h2>How about some links?</h2>
		<div>
			<div class="row">
				<div class="col-6 col-12-small">
					<ul class="link-list">
						<li><a href="#">Sed neque nisi consequat</a></li>
						<li><a href="#">Dapibus sed mattis blandit</a></li>
						<li><a href="#">Quis accumsan lorem</a></li>
						<li><a href="#">Suspendisse varius ipsum</a></li>
						<li><a href="#">Eget et amet consequat</a></li>
					</ul>
				</div>
				<div class="col-6 col-12-small">
					<ul class="link-list">
						<li><a href="#">Quis accumsan lorem</a></li>
						<li><a href="#">Sed neque nisi consequat</a></li>
						<li><a href="#">Eget et amet consequat</a></li>
						<li><a href="#">Dapibus sed mattis blandit</a></li>
						<li><a href="#">Vitae magna sed dolore</a></li>
					</ul>
				</div>
			</div>
		</div>
	</section>
</div>

MyCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>